url: https://notyoursurvivor.github.io
baseurl: /notyoursurvivor

# Site settings
title: Not Your Survivor
email: notyoursurvivor@gmail.com
description: "Not Your Survivor offers a candid exploration of the effects of family sexual abuse, and a road map for how to support loved ones who've been affected by family sexual abuse."


# Team names, titles and social links
people:
- name: Alex Robertson
  pic: 1
  position: Founder, Creative Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: YouTube
    url: 
  - title: Instagram
    url:
  - title: SoundCloud
    url: 


# Postal address (add as many lines as necessary)
address:
  - line: Seattle, WA

# Build settings
markdown: kramdown
permalink: pretty